TARGET=app-pass-firefox
CXX=g++ -std=c++17
CXXFLAGS= -Wall -Werror -Wpedantic -g -MMD
LD=g++
GTKFLAGS=`pkg-config gtkmm-3.0 --cflags --libs` -fsanitize=address
OBJS= main.o pass-firefox.o tools-pass-fox.o
$(TARGET): $(OBJS)
	$(LD) -o $(TARGET) $(OBJS) $(GTKFLAGS)
	# libfontconfig, libpangoft2, and libglib-2.0 used for version 3 of gtkmm have several memory leaks. 
	# However, it can also be a false positive, that is, it can be an irrelevant failure for: asan_thread_start. 
	# Therefore, the command below is equivalent to: export ASAN_OPTIONS=detect_leaks=0 , when run directly in the shell
	@export ASAN_OPTIONS=detect_leaks=0; ./app-pass-firefox # Disable libasan false positive 
	@rm -f *.o *.d

main.o: main.cpp
	$(CXX) -c $(CXXFLAGS) $(GTKFLAGS) main.cpp -o main.o
 
pass-firefox.o: pass-firefox.cpp
	$(CXX) -c $(CXXFLAGS) $(GTKFLAGS) pass-firefox.cpp -o pass-firefox.o

tools-pass-fox.o: tools-pass-fox/tools-pass-fox.cpp
	$(CXX) -c $(CXXFLAGS) tools-pass-fox/tools-pass-fox.cpp -o tools-pass-fox.o
